version: "2.4"
#-------------------------------------------------------------------------------------
#-
#-     login  console               console           rest    ldaps
#-     9031   9999                   8443            1443    1636
#-      |      |                      |               |       |
#-   +---------------+       +---------------+    +---------------+
#-   | PingFederate  |       |PingDataConsole|    | PingDirectory |
#-   +---------------+       +---------------+    +---------------+
#-
#-  PingFederate Console                         PingDataConsole (PingDirectory)
#-  --------------------                         -------------------------------
#-  https://localhost:9999/pingfederate/app      https://localhost:8443
#-    Username: administrator                        Server: pingdirectory
#-    Password: 2FederateM0re                      Username: administrator
#-                                                 Password: 2FederateM0re
#-
#-------------------------------------------------------------------------------------

services:
  pingfederate:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingfederate:10.0.2-edge
    command: wait-for pingdirectory:389 -t 900 -- entrypoint.sh start-server
    environment:
      - SERVER_PROFILE_URL=https://github.com/slavapisarevskiy/scim-lab-docker.git
      - SERVER_PROFILE_PATH=profiles/pingfederate
      - VERBOSE=false
      - MAX_HEAP_SIZE=2048m
    env_file:
      # Configuration file created when setup.sh (Getting-started project root directory) is first run to source
      # devops user/key details for evaluation licenses and for docker image/git tags
      - ${HOME}/.pingidentity/devops
    ports:
      - "9031:9031"
      - "9999:9999"
    networks:
      - pingnet
    volumes:
      - pingfederate-out:/opt/out
      #- ${HOME}/projects/scim-lab-docker/pingfederate-opt-out:/opt/out
      #- ${HOME}/projects/scim-lab-docker/profiles/pingfederate:/opt/in

  pingdirectory:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingdirectory@sha256:fbac17e6f1f7dd0fba3648449b2d0d09604fb6bdd507f18f968cbfab2d7569d7
    environment:
      - SERVER_PROFILE_URL=https://github.com/slavapisarevskiy/scim-lab-docker.git
      - SERVER_PROFILE_PATH=profiles/pingdirectory
      - MAX_HEAP_SIZE=2048m
    env_file:
      - ${HOME}/.pingidentity/devops
    ulimits:
      nproc:
        soft: 16384
        hard: 16384
      nofile:
        soft: 65535
        hard: 65535
    ports:
      - "1636:636"
      - "1443:443"
      - "1389:389"
      - "18080:8080"
    networks:
      - pingnet
    volumes:
      - pingdirectory-out:/opt/out
      #- ${HOME}/projects/scim-lab-docker/pingdirectory-opt-out:/opt/out
      #- ${HOME}/projects/scim-lab-docker/profiles/pingdirectory:/opt/in

  pingdataconsole:
    image: ${PING_IDENTITY_DEVOPS_REGISTRY}/pingdataconsole:${PING_IDENTITY_DEVOPS_TAG}
    ports:
      - "8443:8443"
    networks:
      - pingnet


networks:
    pingnet:

volumes:
  pingfederate-out:
  pingdirectory-out:
